### ISSUE TITLE
Should we show timeslots before now?

### ISSUE THREAD

**Issue by jonathankeebler** [compassdigital/compassdigital.provider.location.bamco#27]
The call https://api.compassdigital.org/v1/location/brand/B5XY4Aq2ljsd4PYAQp70HB92M8jO0v/timeslots will return all the timeslots for today, starting from 0:00 (right?). As a result, we're getting timeslots for 3am etc in the BAMCO app. 

Does it make sense to only return timeslots after the current time (now)?

**Comment by jpdemiranda** [comment]
That makes sense to me ... I'll update the call

**Comment by jonathankeebler** [comment]
Thanks!

**Comment by jonathankeebler** [comment]
@jpdemiranda Is this on v1 yet? If so, go ahead and close this

**Comment by jpdemiranda** [comment]
it is
